Refactor of Harmony base sample project
mobilejazz/harmony-swift pull request #24
Opened 2021-03-22 13:04 UTC by vilanovi

**Note**: This PR includes https://github.com/mobilejazz/harmony-swift/pull/23. First, accept https://github.com/mobilejazz/harmony-swift/pull/23 and then this one.

- Removed Swinject and built a custom ApplicationProvider injection
- Fixed mockable.io API to work
- Moved all "core" code to a new folder structure
- Removed unused realm examples
- Refactored ItemList view controller to common MVP structure

2021-03-23 07:37 UTC, vilanovi commented
Reviewers, please check the ApplicationProvider.swift and ItemProvider.swift to ensure everything is ok and following the standards we have. It's the first time I've written manually the DI, and I could have done wrongly many things (like, for example, the Mappers are being created within the ItemDefaultModule instead by constructor..?)

2021-03-23 10:05 UTC, joselufo requested changes

2021-03-23 10:05 UTC, joselufo commented on Example/Harmony/Core/Features/Item/Domain/Presenters/ItemDetailPresenter.swift
> +    func onSelectedItem(_ item: Item)
These two functions are not using the prefixes specified in the harmony documentation. 

https://harmony.mobilejazz.com/docs/best-practices/presenter-specs

2021-03-23 10:05 UTC, joselufo commented on Example/Harmony/Core/Features/Item/Domain/Presenters/ItemListPresenter.swift
> +}
Not using the prefixes defined in harmony. 
https://harmony.mobilejazz.com/docs/best-practices/presenter-specs

2021-03-23 14:50 UTC, jfilowk approved these changes

2021-05-26 14:47 UTC, vilanovi commented
@joselufo changes applied. Please verify.

2021-05-27 07:32 UTC, joselufo approved these changes

2021-05-27 07:32 UTC, merged