Add a memory reporter protocol and a concrete implemetation
mobilejazz/harmony-swift pull request #30
Opened 2022-02-16 15:51 UTC by newboadki

2022-02-17 08:37 UTC, joselufo approved these changes

2022-02-17 08:37 UTC, victoraga83 approved these changes

2022-02-17 08:39 UTC, jfilowk approved these changes

2022-02-17 08:39 UTC, vilanovi requested changes

2022-02-17 08:39 UTC, vilanovi commented on Sources/Harmony/Common/MemoryReporter.swift
> +        return "RAM: used: \(usedInMB)MB free: \(freeInMB)MB total: \(totalInMB)MB"
@newboadki  no decimals here. just making sure this is the desired behavior.

2022-02-17 08:39 UTC, vilanovi commented on Sources/Harmony/Common/MemoryReporter.swift
> +    let used: UInt64  // In bytes
@newboadki attributes are not public. If not public, they won't be accessible from outside the library.

2022-02-17 08:39 UTC, vilanovi commented on Sources/Harmony/Common/MemoryReporter.swift
> +    func ram() -> RamState?
@newboadki if the struct is called "RamState" wouldn't make sense to call the function "ramState() -> RamState?" ? 

This is a side idea, if you think it is not meaningful, feel free to not apply any change here.

2022-02-17 08:39 UTC, vilanovi commented on Sources/Harmony/Common/MemoryReporter.swift
> +    func ram() -> RamState?
Also, the method is not documented. Would be good to add documentation explaining what it means if it's nil and if it can be called from any thread.

2022-02-17 08:41 UTC, AresProductions commented on Example/Harmony.xcodeproj/project.pbxproj
> +/* Begin PBXShellScriptBuildPhase section */
Please check this section here. Doesn't look right.

2022-02-17 08:43 UTC, AresProductions commented on Example/Harmony.xcodeproj/project.pbxproj
> +
Please check this section here. Doesn't look right.

2022-02-18 08:11 UTC, closed without merging

2022-02-18 08:15 UTC, newboadki commented
Closing this now as it became out of scope. This change was required with to help debug some memory pressure issues that  had certain urgency but a different approach was used that gives us time to revisit in the future the changes in this pull request.