IOS-1859 :: Add RW Testing Outcome in Harmony Swift
mobilejazz/harmony-swift pull request #37
Opened 2022-06-17 08:22 UTC by vilanovi

**Merge / Pull request information**

* Asana task link: https://app.asana.com/0/1109863238977521/1202462981511859/f

Included in the PR:
- Adding number random generator in Harmony.
- Adding DataSoruce and Repository Spy classes in HarmonyTesting.
- Adding Mock ObjectValidation class in HarmonyTesting.
- Adding unit tests for cache and in-memory data source.

The goal of PR is to gather all the outcomes from the RW testing session and include them in the repo. If you guys have more tests to add or want to replace mine for others, you're welcome to do it (I'm not an expert in testing).

2022-07-08 07:40 UTC, franmontiel approved these changes

2022-07-19 13:02 UTC, joselufo requested changes

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        let query = IdQuery("id")
`"id"` should be a random string.

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        let value = 42
`"value"` should be a random value.

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        let value = 42
same as above

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        let query = IdQuery("id")
same as above

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        }
This code could be improved with the following style:

```swift
        var error: Error?
        _ = try dataSoruce.get(query).result.get(error: &error)
        
        let expectedError = CoreError. NotFound("XXXX")
        expect(error).to(matchError(expectedError))
        
        
        // or
        expect { try dataSoruce.get(query).result.get() }.to(throwError(errorType: CoreError. NotFound.self))
```

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        }
same as above

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        }
same as above

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +
empty break line

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        }
same as above

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        let query = IdQuery("id")
Should be a random string

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        }
Could be better to follow another style to check the error, see the in the `InMemoryDataSourceTests`.

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        let query = IdQuery("id")
should be random

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        let query = IdQuery("id")
should be random

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        }
same as above

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        let query = IdQuery("id")
should be random

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        let query = IdQuery("id")
should be random

2022-07-19 13:02 UTC, joselufo commented on Tests/HarmonyTests/CacheRepositoryTests.swift
> +        }
same as above

2022-07-19 13:14 UTC, vilanovi commented on Tests/HarmonyTests/InMemoryDataSourceTests.swift
> +        let query = IdQuery("id")
fixed

2022-07-23 14:43 UTC, joselufo approved these changes

2022-07-23 14:43 UTC, merged